### ISSUE TITLE
Get groups after login

### ISSUE THREAD

**Issue by arnoschrijver80** [stmswitcher/yii2-ldap-auth#2]
Is there a way to check groups after login is performed and store them in session for RBAC?

Thanks in advance

**Comment by stmswitcher** [comment]
Hey @arnoschrijver80.
There's a way to get list of groups, [here](https://github.com/stmswitcher/yii2-ldap-auth/blob/master/src/LdapAuth.php#L186). However, fetching all the groups and storing them is outside of the scope of this extension.

**Comment by arnoschrijver80** [comment]
I believe it's more save to do it in this way:
public function authenticate(string $dn, string $password, string $username, ?string $group = null): bool
    {
        if (!@ldap_bind($this->getConnection(), $dn, $password)) {
            return false;
        }

        if (!$group) {
            return true;
        }

        return $this->isUserInAGroup($username, $group);
    }
private function isUserInAGroup(string $dn, string $group): bool
    {
        $count = 0;
        $search_results = @ldap_search($this->connection, $this->baseDn, '(samaccountname='.$dn.')',  array('*'));
        $search_entries = ldap_get_entries($this->connection, $search_results);
        if($search_entries)
        {
            foreach($search_entries[0]['memberof'] as $key => $adgroup)
            {
                if(is_int($adgroup) == false)
                {
                    $groupExploded = explode(',', $adgroup);
                    $trimmedgroup = ltrim($groupExploded[0], 'CN=');
                    if(strpos($trimmedgroup, $group) === 0)
                    {
                        $_SESSION['groups'][] = $trimmedgroup;
                        $count++;
                    }
                } 
            }
            if($count != 0)
            {
                return true;
            }
        }
        return false;
    }

**Comment by arnoschrijver80** [comment]
It works with this code. Adjusted the form also:
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) 
        {
            $user = LdapUser::findIdentity($this->username);
             if (!$user || !Yii::$app->ldapAuth->authenticate($user->getDn(), $this->password, $this->username, '##GROUPNAME##')) 
            {
                $this->addError($attribute, 'Incorrect username/password or insufficient rights!');
            }
        }
    }
    
and stores the groups in session
