### ISSUE TITLE
facing error:  yii\web\Application::ldapAuth

### ISSUE THREAD

**Issue by sunny29mca** [stmswitcher/yii2-ldap-auth#3]
It's not working from my side , giving error

Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: yii\web\Application::ldapAuth

please share a solution regarding that.

**Comment by stmswitcher** [comment]
Hey @sunny29mca, sorry to hear you're having issues with the package.

Could you let me know if you've added the component to your [config file](https://github.com/stmswitcher/yii2-ldap-auth#configure-the-component-in-your-configuration-file-and-change-user-identity-class)?

**Comment by sunny29mca** [comment]
> Hey @sunny29mca, sorry to hear you're having issues with the package.
> 
> Could you let me know if you've added the component to your [config file](https://github.com/stmswitcher/yii2-ldap-auth#configure-the-component-in-your-configuration-file-and-change-user-identity-class)?




yes did the same and found syntax error ,so  add ) which was missing on if (!$user || !Yii::$app->ldapAuth->authenticate($user->getDn(), $this->password) {

![issue](https://user-images.githubusercontent.com/16384588/219380972-1971c166-5a51-454b-b0d0-fbeda4bd5b49.jpg)

**Comment by sunny29mca** [comment]
![issue](https://user-images.githubusercontent.com/16384588/219382967-106ef6a9-702c-41ef-86e1-8d405eae972a.jpg)
 *Yes did the same and found a syntax error *

*,so add ) which was missing on if (!$user ||
!Yii::$app->ldapAuth->authenticate($user->getDn(), $this->password) {*


*and please find the error screenshot as an attachment.*



Thanks

**Comment by stmswitcher** [comment]
Thx for the hint. Updated the readme.

**Comment by sunny29mca** [comment]
It's not fixed ,please share solution with me.
